<?php

if ($block->enable == 'yes') {
    $block->setTemplate('Eniture_PalletPackaging::/system/config/palletpackagingtab.phtml');
    echo $block->getHtml();
} else {
    ?>
        <div class="palletpackaging">
            <p>
            <?= /* @noEscape */
             __(
                 'Click <a href="%1" target="_blank">here</a> to add the Pallet Packaging module. (<a href="%2" target="_blank">Learn more</a>)',
                 "https://eniture.com/magento2-pallet-packaging/",
                 "https://eniture.com/magento2-pallet-packaging/#documentation"
             )
            ?>
            </p>
        </div>
    <?php
}
