<script>
    require(['jquery','domReady!'], function($){
            var carrierdiv = '#UpsLtlUserGuide_fourth-head';
            upsLtlCurrentPlanNote($, '<?= $block->upsLtlPlanNotice(); ?>', carrierdiv);
    });
</script>
<div class="user-guide">
    <p>
        <?= $block->escapeHtml(__("The User Guide for this application is maintained on the publisher's website. To view it click <a href='%1' target='_blank'>here</a> or paste the following link into your browser.", $block->docUrl), ['a', 'div'])?>
    </p>
    <?= $block->escapeHtml($block->docUrl) ?>
</div>
